// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class Alarm;
@class AlarmBuilder;
@class BalanceQuery;
@class BalanceQueryBuilder;
@class Chat;
@class ChatBuilder;
@class FamilyMember;
@class FamilyMemberBuilder;
@class Fence;
@class FenceBuilder;
@class Location;
@class LocationBuilder;
@class Lock;
@class LockBuilder;
@class Mobile;
@class MobileBuilder;
@class PhoneBook;
@class PhoneBookBuilder;
@class PowerSwitch;
@class PowerSwitchBuilder;
@class Protocols;
@class ProtocolsBuilder;
@class Server;
@class ServerBuilder;
@class Setting;
@class SettingBuilder;
@class Watch;
@class WatchBuilder;
@class Weather;
@class WeatherAlarm;
@class WeatherAlarmBuilder;
@class WeatherBuilder;
@class WeatherForecast;
@class WeatherForecastBuilder;
@class WeatherLive;
@class WeatherLiveBuilder;



@interface SmartWatchRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define Protocols_protocolVersion @"protocolVersion"
#define Protocols_version @"version"
#define Protocols_clientType @"clientType"
#define Protocols_customerId @"customerId"
#define Protocols_reqId @"reqId"
#define Protocols_type @"type"
#define Protocols_watch @"watch"
#define Protocols_mobile @"mobile"
#define Protocols_chat @"chat"
#define Protocols_setting @"setting"
#define Protocols_alarms @"alarms"
#define Protocols_locks @"locks"
#define Protocols_familyMembers @"familyMembers"
#define Protocols_powerSwitch @"powerSwitch"
#define Protocols_fences @"fences"
#define Protocols_server @"server"
#define Protocols_watches @"watches"
#define Protocols_balanceQuery @"balanceQuery"
#define Protocols_phoneBooks @"phoneBooks"
#define Protocols_weather @"weather"
#define Protocols_message @"message"
@interface Protocols : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasReqId_:1;
  BOOL hasVersion_:1;
  BOOL hasWatch_:1;
  BOOL hasMobile_:1;
  BOOL hasChat_:1;
  BOOL hasSetting_:1;
  BOOL hasPowerSwitch_:1;
  BOOL hasServer_:1;
  BOOL hasWeather_:1;
  BOOL hasProtocolVersion_:1;
  BOOL hasClientType_:1;
  BOOL hasCustomerId_:1;
  BOOL hasType_:1;
  UInt64 reqId;
  NSString* version;
  Watch* watch;
  Mobile* mobile;
  Chat* chat;
  Setting* setting;
  PowerSwitch* powerSwitch;
  Server* server;
  Weather* weather;
  UInt32 protocolVersion;
  UInt32 clientType;
  UInt32 customerId;
  UInt32 type;
  NSMutableArray * messageArray;
  NSMutableArray * alarmsArray;
  NSMutableArray * locksArray;
  NSMutableArray * familyMembersArray;
  NSMutableArray * fencesArray;
  NSMutableArray * watchesArray;
  NSMutableArray * balanceQueryArray;
  NSMutableArray * phoneBooksArray;
}
- (BOOL) hasProtocolVersion;
- (BOOL) hasVersion;
- (BOOL) hasClientType;
- (BOOL) hasCustomerId;
- (BOOL) hasReqId;
- (BOOL) hasType;
- (BOOL) hasWatch;
- (BOOL) hasMobile;
- (BOOL) hasChat;
- (BOOL) hasSetting;
- (BOOL) hasPowerSwitch;
- (BOOL) hasServer;
- (BOOL) hasWeather;
@property (readonly) UInt32 protocolVersion;
@property (readonly, strong) NSString* version;
@property (readonly) UInt32 clientType;
@property (readonly) UInt32 customerId;
@property (readonly) UInt64 reqId;
@property (readonly) UInt32 type;
@property (readonly, strong) Watch* watch;
@property (readonly, strong) Mobile* mobile;
@property (readonly, strong) Chat* chat;
@property (readonly, strong) Setting* setting;
@property (readonly, strong) NSArray * alarms;
@property (readonly, strong) NSArray * locks;
@property (readonly, strong) NSArray * familyMembers;
@property (readonly, strong) PowerSwitch* powerSwitch;
@property (readonly, strong) NSArray * fences;
@property (readonly, strong) Server* server;
@property (readonly, strong) NSArray * watches;
@property (readonly, strong) NSArray * balanceQuery;
@property (readonly, strong) NSArray * phoneBooks;
@property (readonly, strong) Weather* weather;
@property (readonly, strong) NSArray * message;
- (Alarm*)alarmsAtIndex:(NSUInteger)index;
- (Lock*)locksAtIndex:(NSUInteger)index;
- (FamilyMember*)familyMembersAtIndex:(NSUInteger)index;
- (Fence*)fencesAtIndex:(NSUInteger)index;
- (Watch*)watchesAtIndex:(NSUInteger)index;
- (BalanceQuery*)balanceQueryAtIndex:(NSUInteger)index;
- (PhoneBook*)phoneBooksAtIndex:(NSUInteger)index;
- (NSString*)messageAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ProtocolsBuilder*) builder;
+ (ProtocolsBuilder*) builder;
+ (ProtocolsBuilder*) builderWithPrototype:(Protocols*) prototype;
- (ProtocolsBuilder*) toBuilder;

+ (Protocols*) parseFromData:(NSData*) data;
+ (Protocols*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Protocols*) parseFromInputStream:(NSInputStream*) input;
+ (Protocols*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Protocols*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Protocols*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ProtocolsBuilder : PBGeneratedMessageBuilder {
@private
  Protocols* resultProtocols;
}

- (Protocols*) defaultInstance;

- (ProtocolsBuilder*) clear;
- (ProtocolsBuilder*) clone;

- (Protocols*) build;
- (Protocols*) buildPartial;

- (ProtocolsBuilder*) mergeFrom:(Protocols*) other;
- (ProtocolsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ProtocolsBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasProtocolVersion;
- (UInt32) protocolVersion;
- (ProtocolsBuilder*) setProtocolVersion:(UInt32) value;
- (ProtocolsBuilder*) clearProtocolVersion;

- (BOOL) hasVersion;
- (NSString*) version;
- (ProtocolsBuilder*) setVersion:(NSString*) value;
- (ProtocolsBuilder*) clearVersion;

- (BOOL) hasClientType;
- (UInt32) clientType;
- (ProtocolsBuilder*) setClientType:(UInt32) value;
- (ProtocolsBuilder*) clearClientType;

- (BOOL) hasCustomerId;
- (UInt32) customerId;
- (ProtocolsBuilder*) setCustomerId:(UInt32) value;
- (ProtocolsBuilder*) clearCustomerId;

- (BOOL) hasReqId;
- (UInt64) reqId;
- (ProtocolsBuilder*) setReqId:(UInt64) value;
- (ProtocolsBuilder*) clearReqId;

- (BOOL) hasType;
- (UInt32) type;
- (ProtocolsBuilder*) setType:(UInt32) value;
- (ProtocolsBuilder*) clearType;

- (BOOL) hasWatch;
- (Watch*) watch;
- (ProtocolsBuilder*) setWatch:(Watch*) value;
- (ProtocolsBuilder*) setWatchBuilder:(WatchBuilder*) builderForValue;
- (ProtocolsBuilder*) mergeWatch:(Watch*) value;
- (ProtocolsBuilder*) clearWatch;

- (BOOL) hasMobile;
- (Mobile*) mobile;
- (ProtocolsBuilder*) setMobile:(Mobile*) value;
- (ProtocolsBuilder*) setMobileBuilder:(MobileBuilder*) builderForValue;
- (ProtocolsBuilder*) mergeMobile:(Mobile*) value;
- (ProtocolsBuilder*) clearMobile;

- (BOOL) hasChat;
- (Chat*) chat;
- (ProtocolsBuilder*) setChat:(Chat*) value;
- (ProtocolsBuilder*) setChatBuilder:(ChatBuilder*) builderForValue;
- (ProtocolsBuilder*) mergeChat:(Chat*) value;
- (ProtocolsBuilder*) clearChat;

- (BOOL) hasSetting;
- (Setting*) setting;
- (ProtocolsBuilder*) setSetting:(Setting*) value;
- (ProtocolsBuilder*) setSettingBuilder:(SettingBuilder*) builderForValue;
- (ProtocolsBuilder*) mergeSetting:(Setting*) value;
- (ProtocolsBuilder*) clearSetting;

- (NSMutableArray *)alarms;
- (Alarm*)alarmsAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addAlarms:(Alarm*)value;
- (ProtocolsBuilder *)setAlarmsArray:(NSArray *)array;
- (ProtocolsBuilder *)clearAlarms;

- (NSMutableArray *)locks;
- (Lock*)locksAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addLocks:(Lock*)value;
- (ProtocolsBuilder *)setLocksArray:(NSArray *)array;
- (ProtocolsBuilder *)clearLocks;

- (NSMutableArray *)familyMembers;
- (FamilyMember*)familyMembersAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addFamilyMembers:(FamilyMember*)value;
- (ProtocolsBuilder *)setFamilyMembersArray:(NSArray *)array;
- (ProtocolsBuilder *)clearFamilyMembers;

- (BOOL) hasPowerSwitch;
- (PowerSwitch*) powerSwitch;
- (ProtocolsBuilder*) setPowerSwitch:(PowerSwitch*) value;
- (ProtocolsBuilder*) setPowerSwitchBuilder:(PowerSwitchBuilder*) builderForValue;
- (ProtocolsBuilder*) mergePowerSwitch:(PowerSwitch*) value;
- (ProtocolsBuilder*) clearPowerSwitch;

- (NSMutableArray *)fences;
- (Fence*)fencesAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addFences:(Fence*)value;
- (ProtocolsBuilder *)setFencesArray:(NSArray *)array;
- (ProtocolsBuilder *)clearFences;

- (BOOL) hasServer;
- (Server*) server;
- (ProtocolsBuilder*) setServer:(Server*) value;
- (ProtocolsBuilder*) setServerBuilder:(ServerBuilder*) builderForValue;
- (ProtocolsBuilder*) mergeServer:(Server*) value;
- (ProtocolsBuilder*) clearServer;

- (NSMutableArray *)watches;
- (Watch*)watchesAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addWatches:(Watch*)value;
- (ProtocolsBuilder *)setWatchesArray:(NSArray *)array;
- (ProtocolsBuilder *)clearWatches;

- (NSMutableArray *)balanceQuery;
- (BalanceQuery*)balanceQueryAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addBalanceQuery:(BalanceQuery*)value;
- (ProtocolsBuilder *)setBalanceQueryArray:(NSArray *)array;
- (ProtocolsBuilder *)clearBalanceQuery;

- (NSMutableArray *)phoneBooks;
- (PhoneBook*)phoneBooksAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addPhoneBooks:(PhoneBook*)value;
- (ProtocolsBuilder *)setPhoneBooksArray:(NSArray *)array;
- (ProtocolsBuilder *)clearPhoneBooks;

- (BOOL) hasWeather;
- (Weather*) weather;
- (ProtocolsBuilder*) setWeather:(Weather*) value;
- (ProtocolsBuilder*) setWeatherBuilder:(WeatherBuilder*) builderForValue;
- (ProtocolsBuilder*) mergeWeather:(Weather*) value;
- (ProtocolsBuilder*) clearWeather;

- (NSMutableArray *)message;
- (NSString*)messageAtIndex:(NSUInteger)index;
- (ProtocolsBuilder *)addMessage:(NSString*)value;
- (ProtocolsBuilder *)setMessageArray:(NSArray *)array;
- (ProtocolsBuilder *)clearMessage;
@end

#define Weather_live @"live"
#define Weather_forecasts @"forecasts"
#define Weather_alarms @"alarms"
@interface Weather : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLive_:1;
  WeatherLive* live;
  NSMutableArray * forecastsArray;
  NSMutableArray * alarmsArray;
}
- (BOOL) hasLive;
@property (readonly, strong) WeatherLive* live;
@property (readonly, strong) NSArray * forecasts;
@property (readonly, strong) NSArray * alarms;
- (WeatherForecast*)forecastsAtIndex:(NSUInteger)index;
- (WeatherAlarm*)alarmsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WeatherBuilder*) builder;
+ (WeatherBuilder*) builder;
+ (WeatherBuilder*) builderWithPrototype:(Weather*) prototype;
- (WeatherBuilder*) toBuilder;

+ (Weather*) parseFromData:(NSData*) data;
+ (Weather*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Weather*) parseFromInputStream:(NSInputStream*) input;
+ (Weather*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Weather*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Weather*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WeatherBuilder : PBGeneratedMessageBuilder {
@private
  Weather* resultWeather;
}

- (Weather*) defaultInstance;

- (WeatherBuilder*) clear;
- (WeatherBuilder*) clone;

- (Weather*) build;
- (Weather*) buildPartial;

- (WeatherBuilder*) mergeFrom:(Weather*) other;
- (WeatherBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WeatherBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLive;
- (WeatherLive*) live;
- (WeatherBuilder*) setLive:(WeatherLive*) value;
- (WeatherBuilder*) setLiveBuilder:(WeatherLiveBuilder*) builderForValue;
- (WeatherBuilder*) mergeLive:(WeatherLive*) value;
- (WeatherBuilder*) clearLive;

- (NSMutableArray *)forecasts;
- (WeatherForecast*)forecastsAtIndex:(NSUInteger)index;
- (WeatherBuilder *)addForecasts:(WeatherForecast*)value;
- (WeatherBuilder *)setForecastsArray:(NSArray *)array;
- (WeatherBuilder *)clearForecasts;

- (NSMutableArray *)alarms;
- (WeatherAlarm*)alarmsAtIndex:(NSUInteger)index;
- (WeatherBuilder *)addAlarms:(WeatherAlarm*)value;
- (WeatherBuilder *)setAlarmsArray:(NSArray *)array;
- (WeatherBuilder *)clearAlarms;
@end

#define WeatherLive_status @"status"
#define WeatherLive_temp @"temp"
#define WeatherLive_humidity @"humidity"
#define WeatherLive_windDirection @"windDirection"
#define WeatherLive_windSpeed @"windSpeed"
#define WeatherLive_vis @"vis"
#define WeatherLive_aqi @"aqi"
#define WeatherLive_statusTxt @"statusTxt"
@interface WeatherLive : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasWindDirection_:1;
  BOOL hasWindSpeed_:1;
  BOOL hasVis_:1;
  BOOL hasAqi_:1;
  BOOL hasStatusTxt_:1;
  BOOL hasStatus_:1;
  BOOL hasTemp_:1;
  BOOL hasHumidity_:1;
  NSString* windDirection;
  NSString* windSpeed;
  NSString* vis;
  NSString* aqi;
  NSString* statusTxt;
  UInt32 status;
  UInt32 temp;
  UInt32 humidity;
}
- (BOOL) hasStatus;
- (BOOL) hasTemp;
- (BOOL) hasHumidity;
- (BOOL) hasWindDirection;
- (BOOL) hasWindSpeed;
- (BOOL) hasVis;
- (BOOL) hasAqi;
- (BOOL) hasStatusTxt;
@property (readonly) UInt32 status;
@property (readonly) UInt32 temp;
@property (readonly) UInt32 humidity;
@property (readonly, strong) NSString* windDirection;
@property (readonly, strong) NSString* windSpeed;
@property (readonly, strong) NSString* vis;
@property (readonly, strong) NSString* aqi;
@property (readonly, strong) NSString* statusTxt;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WeatherLiveBuilder*) builder;
+ (WeatherLiveBuilder*) builder;
+ (WeatherLiveBuilder*) builderWithPrototype:(WeatherLive*) prototype;
- (WeatherLiveBuilder*) toBuilder;

+ (WeatherLive*) parseFromData:(NSData*) data;
+ (WeatherLive*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WeatherLive*) parseFromInputStream:(NSInputStream*) input;
+ (WeatherLive*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WeatherLive*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WeatherLive*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WeatherLiveBuilder : PBGeneratedMessageBuilder {
@private
  WeatherLive* resultWeatherLive;
}

- (WeatherLive*) defaultInstance;

- (WeatherLiveBuilder*) clear;
- (WeatherLiveBuilder*) clone;

- (WeatherLive*) build;
- (WeatherLive*) buildPartial;

- (WeatherLiveBuilder*) mergeFrom:(WeatherLive*) other;
- (WeatherLiveBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WeatherLiveBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasStatus;
- (UInt32) status;
- (WeatherLiveBuilder*) setStatus:(UInt32) value;
- (WeatherLiveBuilder*) clearStatus;

- (BOOL) hasTemp;
- (UInt32) temp;
- (WeatherLiveBuilder*) setTemp:(UInt32) value;
- (WeatherLiveBuilder*) clearTemp;

- (BOOL) hasHumidity;
- (UInt32) humidity;
- (WeatherLiveBuilder*) setHumidity:(UInt32) value;
- (WeatherLiveBuilder*) clearHumidity;

- (BOOL) hasWindDirection;
- (NSString*) windDirection;
- (WeatherLiveBuilder*) setWindDirection:(NSString*) value;
- (WeatherLiveBuilder*) clearWindDirection;

- (BOOL) hasWindSpeed;
- (NSString*) windSpeed;
- (WeatherLiveBuilder*) setWindSpeed:(NSString*) value;
- (WeatherLiveBuilder*) clearWindSpeed;

- (BOOL) hasVis;
- (NSString*) vis;
- (WeatherLiveBuilder*) setVis:(NSString*) value;
- (WeatherLiveBuilder*) clearVis;

- (BOOL) hasAqi;
- (NSString*) aqi;
- (WeatherLiveBuilder*) setAqi:(NSString*) value;
- (WeatherLiveBuilder*) clearAqi;

- (BOOL) hasStatusTxt;
- (NSString*) statusTxt;
- (WeatherLiveBuilder*) setStatusTxt:(NSString*) value;
- (WeatherLiveBuilder*) clearStatusTxt;
@end

#define WeatherForecast_day @"day"
#define WeatherForecast_dayStatus @"dayStatus"
#define WeatherForecast_nightStatus @"nightStatus"
#define WeatherForecast_tempMax @"tempMax"
#define WeatherForecast_tempMin @"tempMin"
#define WeatherForecast_humidity @"humidity"
#define WeatherForecast_windDirection @"windDirection"
#define WeatherForecast_windSpeed @"windSpeed"
#define WeatherForecast_vis @"vis"
#define WeatherForecast_dayStatusTxt @"dayStatusTxt"
#define WeatherForecast_nightStatusTxt @"nightStatusTxt"
@interface WeatherForecast : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasDay_:1;
  BOOL hasWindDirection_:1;
  BOOL hasWindSpeed_:1;
  BOOL hasVis_:1;
  BOOL hasDayStatusTxt_:1;
  BOOL hasNightStatusTxt_:1;
  BOOL hasDayStatus_:1;
  BOOL hasNightStatus_:1;
  BOOL hasTempMax_:1;
  BOOL hasTempMin_:1;
  BOOL hasHumidity_:1;
  UInt64 day;
  NSString* windDirection;
  NSString* windSpeed;
  NSString* vis;
  NSString* dayStatusTxt;
  NSString* nightStatusTxt;
  UInt32 dayStatus;
  UInt32 nightStatus;
  UInt32 tempMax;
  UInt32 tempMin;
  UInt32 humidity;
}
- (BOOL) hasDay;
- (BOOL) hasDayStatus;
- (BOOL) hasNightStatus;
- (BOOL) hasTempMax;
- (BOOL) hasTempMin;
- (BOOL) hasHumidity;
- (BOOL) hasWindDirection;
- (BOOL) hasWindSpeed;
- (BOOL) hasVis;
- (BOOL) hasDayStatusTxt;
- (BOOL) hasNightStatusTxt;
@property (readonly) UInt64 day;
@property (readonly) UInt32 dayStatus;
@property (readonly) UInt32 nightStatus;
@property (readonly) UInt32 tempMax;
@property (readonly) UInt32 tempMin;
@property (readonly) UInt32 humidity;
@property (readonly, strong) NSString* windDirection;
@property (readonly, strong) NSString* windSpeed;
@property (readonly, strong) NSString* vis;
@property (readonly, strong) NSString* dayStatusTxt;
@property (readonly, strong) NSString* nightStatusTxt;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WeatherForecastBuilder*) builder;
+ (WeatherForecastBuilder*) builder;
+ (WeatherForecastBuilder*) builderWithPrototype:(WeatherForecast*) prototype;
- (WeatherForecastBuilder*) toBuilder;

+ (WeatherForecast*) parseFromData:(NSData*) data;
+ (WeatherForecast*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WeatherForecast*) parseFromInputStream:(NSInputStream*) input;
+ (WeatherForecast*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WeatherForecast*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WeatherForecast*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WeatherForecastBuilder : PBGeneratedMessageBuilder {
@private
  WeatherForecast* resultWeatherForecast;
}

- (WeatherForecast*) defaultInstance;

- (WeatherForecastBuilder*) clear;
- (WeatherForecastBuilder*) clone;

- (WeatherForecast*) build;
- (WeatherForecast*) buildPartial;

- (WeatherForecastBuilder*) mergeFrom:(WeatherForecast*) other;
- (WeatherForecastBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WeatherForecastBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDay;
- (UInt64) day;
- (WeatherForecastBuilder*) setDay:(UInt64) value;
- (WeatherForecastBuilder*) clearDay;

- (BOOL) hasDayStatus;
- (UInt32) dayStatus;
- (WeatherForecastBuilder*) setDayStatus:(UInt32) value;
- (WeatherForecastBuilder*) clearDayStatus;

- (BOOL) hasNightStatus;
- (UInt32) nightStatus;
- (WeatherForecastBuilder*) setNightStatus:(UInt32) value;
- (WeatherForecastBuilder*) clearNightStatus;

- (BOOL) hasTempMax;
- (UInt32) tempMax;
- (WeatherForecastBuilder*) setTempMax:(UInt32) value;
- (WeatherForecastBuilder*) clearTempMax;

- (BOOL) hasTempMin;
- (UInt32) tempMin;
- (WeatherForecastBuilder*) setTempMin:(UInt32) value;
- (WeatherForecastBuilder*) clearTempMin;

- (BOOL) hasHumidity;
- (UInt32) humidity;
- (WeatherForecastBuilder*) setHumidity:(UInt32) value;
- (WeatherForecastBuilder*) clearHumidity;

- (BOOL) hasWindDirection;
- (NSString*) windDirection;
- (WeatherForecastBuilder*) setWindDirection:(NSString*) value;
- (WeatherForecastBuilder*) clearWindDirection;

- (BOOL) hasWindSpeed;
- (NSString*) windSpeed;
- (WeatherForecastBuilder*) setWindSpeed:(NSString*) value;
- (WeatherForecastBuilder*) clearWindSpeed;

- (BOOL) hasVis;
- (NSString*) vis;
- (WeatherForecastBuilder*) setVis:(NSString*) value;
- (WeatherForecastBuilder*) clearVis;

- (BOOL) hasDayStatusTxt;
- (NSString*) dayStatusTxt;
- (WeatherForecastBuilder*) setDayStatusTxt:(NSString*) value;
- (WeatherForecastBuilder*) clearDayStatusTxt;

- (BOOL) hasNightStatusTxt;
- (NSString*) nightStatusTxt;
- (WeatherForecastBuilder*) setNightStatusTxt:(NSString*) value;
- (WeatherForecastBuilder*) clearNightStatusTxt;
@end

#define WeatherAlarm_level @"level"
#define WeatherAlarm_state @"state"
#define WeatherAlarm_title @"title"
#define WeatherAlarm_txt @"txt"
#define WeatherAlarm_type @"type"
@interface WeatherAlarm : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLevel_:1;
  BOOL hasState_:1;
  BOOL hasTitle_:1;
  BOOL hasTxt_:1;
  BOOL hasType_:1;
  NSString* level;
  NSString* state;
  NSString* title;
  NSString* txt;
  NSString* type;
}
- (BOOL) hasLevel;
- (BOOL) hasState;
- (BOOL) hasTitle;
- (BOOL) hasTxt;
- (BOOL) hasType;
@property (readonly, strong) NSString* level;
@property (readonly, strong) NSString* state;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* txt;
@property (readonly, strong) NSString* type;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WeatherAlarmBuilder*) builder;
+ (WeatherAlarmBuilder*) builder;
+ (WeatherAlarmBuilder*) builderWithPrototype:(WeatherAlarm*) prototype;
- (WeatherAlarmBuilder*) toBuilder;

+ (WeatherAlarm*) parseFromData:(NSData*) data;
+ (WeatherAlarm*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WeatherAlarm*) parseFromInputStream:(NSInputStream*) input;
+ (WeatherAlarm*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (WeatherAlarm*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (WeatherAlarm*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WeatherAlarmBuilder : PBGeneratedMessageBuilder {
@private
  WeatherAlarm* resultWeatherAlarm;
}

- (WeatherAlarm*) defaultInstance;

- (WeatherAlarmBuilder*) clear;
- (WeatherAlarmBuilder*) clone;

- (WeatherAlarm*) build;
- (WeatherAlarm*) buildPartial;

- (WeatherAlarmBuilder*) mergeFrom:(WeatherAlarm*) other;
- (WeatherAlarmBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WeatherAlarmBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasLevel;
- (NSString*) level;
- (WeatherAlarmBuilder*) setLevel:(NSString*) value;
- (WeatherAlarmBuilder*) clearLevel;

- (BOOL) hasState;
- (NSString*) state;
- (WeatherAlarmBuilder*) setState:(NSString*) value;
- (WeatherAlarmBuilder*) clearState;

- (BOOL) hasTitle;
- (NSString*) title;
- (WeatherAlarmBuilder*) setTitle:(NSString*) value;
- (WeatherAlarmBuilder*) clearTitle;

- (BOOL) hasTxt;
- (NSString*) txt;
- (WeatherAlarmBuilder*) setTxt:(NSString*) value;
- (WeatherAlarmBuilder*) clearTxt;

- (BOOL) hasType;
- (NSString*) type;
- (WeatherAlarmBuilder*) setType:(NSString*) value;
- (WeatherAlarmBuilder*) clearType;
@end

#define PhoneBook_nickName @"nickName"
#define PhoneBook_number @"number"
#define PhoneBook_isFather @"isFather"
#define PhoneBook_isMother @"isMother"
@interface PhoneBook : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsFather_:1;
  BOOL hasIsMother_:1;
  BOOL hasNumber_:1;
  BOOL hasNickName_:1;
  BOOL isFather_:1;
  BOOL isMother_:1;
  UInt64 number;
  NSString* nickName;
}
- (BOOL) hasNickName;
- (BOOL) hasNumber;
- (BOOL) hasIsFather;
- (BOOL) hasIsMother;
@property (readonly, strong) NSString* nickName;
@property (readonly) UInt64 number;
- (BOOL) isFather;
- (BOOL) isMother;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PhoneBookBuilder*) builder;
+ (PhoneBookBuilder*) builder;
+ (PhoneBookBuilder*) builderWithPrototype:(PhoneBook*) prototype;
- (PhoneBookBuilder*) toBuilder;

+ (PhoneBook*) parseFromData:(NSData*) data;
+ (PhoneBook*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PhoneBook*) parseFromInputStream:(NSInputStream*) input;
+ (PhoneBook*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PhoneBook*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PhoneBook*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PhoneBookBuilder : PBGeneratedMessageBuilder {
@private
  PhoneBook* resultPhoneBook;
}

- (PhoneBook*) defaultInstance;

- (PhoneBookBuilder*) clear;
- (PhoneBookBuilder*) clone;

- (PhoneBook*) build;
- (PhoneBook*) buildPartial;

- (PhoneBookBuilder*) mergeFrom:(PhoneBook*) other;
- (PhoneBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PhoneBookBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (PhoneBookBuilder*) setNickName:(NSString*) value;
- (PhoneBookBuilder*) clearNickName;

- (BOOL) hasNumber;
- (UInt64) number;
- (PhoneBookBuilder*) setNumber:(UInt64) value;
- (PhoneBookBuilder*) clearNumber;

- (BOOL) hasIsFather;
- (BOOL) isFather;
- (PhoneBookBuilder*) setIsFather:(BOOL) value;
- (PhoneBookBuilder*) clearIsFather;

- (BOOL) hasIsMother;
- (BOOL) isMother;
- (PhoneBookBuilder*) setIsMother:(BOOL) value;
- (PhoneBookBuilder*) clearIsMother;
@end

#define BalanceQuery_smsPort @"smsPort"
#define BalanceQuery_msg @"msg"
@interface BalanceQuery : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMsg_:1;
  BOOL hasSmsPort_:1;
  NSString* msg;
  UInt32 smsPort;
}
- (BOOL) hasSmsPort;
- (BOOL) hasMsg;
@property (readonly) UInt32 smsPort;
@property (readonly, strong) NSString* msg;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (BalanceQueryBuilder*) builder;
+ (BalanceQueryBuilder*) builder;
+ (BalanceQueryBuilder*) builderWithPrototype:(BalanceQuery*) prototype;
- (BalanceQueryBuilder*) toBuilder;

+ (BalanceQuery*) parseFromData:(NSData*) data;
+ (BalanceQuery*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BalanceQuery*) parseFromInputStream:(NSInputStream*) input;
+ (BalanceQuery*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (BalanceQuery*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (BalanceQuery*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface BalanceQueryBuilder : PBGeneratedMessageBuilder {
@private
  BalanceQuery* resultBalanceQuery;
}

- (BalanceQuery*) defaultInstance;

- (BalanceQueryBuilder*) clear;
- (BalanceQueryBuilder*) clone;

- (BalanceQuery*) build;
- (BalanceQuery*) buildPartial;

- (BalanceQueryBuilder*) mergeFrom:(BalanceQuery*) other;
- (BalanceQueryBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (BalanceQueryBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSmsPort;
- (UInt32) smsPort;
- (BalanceQueryBuilder*) setSmsPort:(UInt32) value;
- (BalanceQueryBuilder*) clearSmsPort;

- (BOOL) hasMsg;
- (NSString*) msg;
- (BalanceQueryBuilder*) setMsg:(NSString*) value;
- (BalanceQueryBuilder*) clearMsg;
@end

#define Server_ips @"ips"
#define Server_serverTime @"serverTime"
#define Server_status @"status"
#define Server_msg @"msg"
#define Server_smsPort @"smsPort"
@interface Server : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasServerTime_:1;
  BOOL hasSmsPort_:1;
  BOOL hasMsg_:1;
  BOOL hasStatus_:1;
  UInt64 serverTime;
  UInt64 smsPort;
  NSString* msg;
  UInt32 status;
  NSMutableArray * ipsArray;
}
- (BOOL) hasServerTime;
- (BOOL) hasStatus;
- (BOOL) hasMsg;
- (BOOL) hasSmsPort;
@property (readonly, strong) NSArray * ips;
@property (readonly) UInt64 serverTime;
@property (readonly) UInt32 status;
@property (readonly, strong) NSString* msg;
@property (readonly) UInt64 smsPort;
- (NSData*)ipsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ServerBuilder*) builder;
+ (ServerBuilder*) builder;
+ (ServerBuilder*) builderWithPrototype:(Server*) prototype;
- (ServerBuilder*) toBuilder;

+ (Server*) parseFromData:(NSData*) data;
+ (Server*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Server*) parseFromInputStream:(NSInputStream*) input;
+ (Server*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Server*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Server*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ServerBuilder : PBGeneratedMessageBuilder {
@private
  Server* resultServer;
}

- (Server*) defaultInstance;

- (ServerBuilder*) clear;
- (ServerBuilder*) clone;

- (Server*) build;
- (Server*) buildPartial;

- (ServerBuilder*) mergeFrom:(Server*) other;
- (ServerBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ServerBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)ips;
- (NSData*)ipsAtIndex:(NSUInteger)index;
- (ServerBuilder *)addIps:(NSData*)value;
- (ServerBuilder *)setIpsArray:(NSArray *)array;
- (ServerBuilder *)clearIps;

- (BOOL) hasServerTime;
- (UInt64) serverTime;
- (ServerBuilder*) setServerTime:(UInt64) value;
- (ServerBuilder*) clearServerTime;

- (BOOL) hasStatus;
- (UInt32) status;
- (ServerBuilder*) setStatus:(UInt32) value;
- (ServerBuilder*) clearStatus;

- (BOOL) hasMsg;
- (NSString*) msg;
- (ServerBuilder*) setMsg:(NSString*) value;
- (ServerBuilder*) clearMsg;

- (BOOL) hasSmsPort;
- (UInt64) smsPort;
- (ServerBuilder*) setSmsPort:(UInt64) value;
- (ServerBuilder*) clearSmsPort;
@end

#define Watch_id @"id"
#define Watch_nickName @"nickName"
#define Watch_number @"number"
#define Watch_imsi @"imsi"
#define Watch_imei @"imei"
#define Watch_locationType @"locationType"
#define Watch_lon @"lon"
#define Watch_lat @"lat"
#define Watch_location @"location"
#define Watch_battery @"battery"
#define Watch_age @"age"
#define Watch_grade @"grade"
#define Watch_avatar @"avatar"
#define Watch_gender @"gender"
#define Watch_height @"height"
#define Watch_weight @"weight"
#define Watch_loveCount @"loveCount"
#define Watch_status @"status"
#define Watch_locations @"locations"
#define Watch_volume @"volume"
#define Watch_qrCode @"qrCode"
#define Watch_qrCodePic @"qrCodePic"
#define Watch_latestLoginTime @"latestLoginTime"
#define Watch_lightSensorOn @"lightSensorOn"
#define Watch_lightSensorStatus @"lightSensorStatus"
#define Watch_gmotionOn @"gmotionOn"
#define Watch_gmotionSteps @"gmotionSteps"
#define Watch_langString @"langString"
@interface Watch : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLon_:1;
  BOOL hasLat_:1;
  BOOL hasId_:1;
  BOOL hasNumber_:1;
  BOOL hasImsi_:1;
  BOOL hasImei_:1;
  BOOL hasLatestLoginTime_:1;
  BOOL hasNickName_:1;
  BOOL hasLocation_:1;
  BOOL hasAvatar_:1;
  BOOL hasQrCode_:1;
  BOOL hasQrCodePic_:1;
  BOOL hasLocationType_:1;
  BOOL hasBattery_:1;
  BOOL hasAge_:1;
  BOOL hasGrade_:1;
  BOOL hasGender_:1;
  BOOL hasHeight_:1;
  BOOL hasWeight_:1;
  BOOL hasLoveCount_:1;
  BOOL hasStatus_:1;
  BOOL hasVolume_:1;
  BOOL hasLightSensorOn_:1;
  BOOL hasLightSensorStatus_:1;
  BOOL hasGmotionOn_:1;
  BOOL hasGmotionSteps_:1;
  BOOL hasLangString_:1;
  Float64 lon;
  Float64 lat;
  UInt64 id;
  UInt64 number;
  UInt64 imsi;
  UInt64 imei;
  UInt64 latestLoginTime;
  NSString* nickName;
  NSString* location;
  NSString* avatar;
  NSString* qrCode;
  NSData* qrCodePic;
  UInt32 locationType;
  UInt32 battery;
  UInt32 age;
  UInt32 grade;
  UInt32 gender;
  UInt32 height;
  UInt32 weight;
  UInt32 loveCount;
  UInt32 status;
  UInt32 volume;
  UInt32 lightSensorOn;
  UInt32 lightSensorStatus;
  UInt32 gmotionOn;
  UInt32 gmotionSteps;
  UInt32 langString;
  NSMutableArray * locationsArray;
}
- (BOOL) hasId;
- (BOOL) hasNickName;
- (BOOL) hasNumber;
- (BOOL) hasImsi;
- (BOOL) hasImei;
- (BOOL) hasLocationType;
- (BOOL) hasLon;
- (BOOL) hasLat;
- (BOOL) hasLocation;
- (BOOL) hasBattery;
- (BOOL) hasAge;
- (BOOL) hasGrade;
- (BOOL) hasAvatar;
- (BOOL) hasGender;
- (BOOL) hasHeight;
- (BOOL) hasWeight;
- (BOOL) hasLoveCount;
- (BOOL) hasStatus;
- (BOOL) hasVolume;
- (BOOL) hasQrCode;
- (BOOL) hasQrCodePic;
- (BOOL) hasLatestLoginTime;
- (BOOL) hasLightSensorOn;
- (BOOL) hasLightSensorStatus;
- (BOOL) hasGmotionOn;
- (BOOL) hasGmotionSteps;
- (BOOL) hasLangString;
@property (readonly) UInt64 id;
@property (readonly, strong) NSString* nickName;
@property (readonly) UInt64 number;
@property (readonly) UInt64 imsi;
@property (readonly) UInt64 imei;
@property (readonly) UInt32 locationType;
@property (readonly) Float64 lon;
@property (readonly) Float64 lat;
@property (readonly, strong) NSString* location;
@property (readonly) UInt32 battery;
@property (readonly) UInt32 age;
@property (readonly) UInt32 grade;
@property (readonly, strong) NSString* avatar;
@property (readonly) UInt32 gender;
@property (readonly) UInt32 height;
@property (readonly) UInt32 weight;
@property (readonly) UInt32 loveCount;
@property (readonly) UInt32 status;
@property (readonly, strong) NSArray * locations;
@property (readonly) UInt32 volume;
@property (readonly, strong) NSString* qrCode;
@property (readonly, strong) NSData* qrCodePic;
@property (readonly) UInt64 latestLoginTime;
@property (readonly) UInt32 lightSensorOn;
@property (readonly) UInt32 lightSensorStatus;
@property (readonly) UInt32 gmotionOn;
@property (readonly) UInt32 gmotionSteps;
@property (readonly) UInt32 langString;
- (Location*)locationsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (WatchBuilder*) builder;
+ (WatchBuilder*) builder;
+ (WatchBuilder*) builderWithPrototype:(Watch*) prototype;
- (WatchBuilder*) toBuilder;

+ (Watch*) parseFromData:(NSData*) data;
+ (Watch*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Watch*) parseFromInputStream:(NSInputStream*) input;
+ (Watch*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Watch*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Watch*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface WatchBuilder : PBGeneratedMessageBuilder {
@private
  Watch* resultWatch;
}

- (Watch*) defaultInstance;

- (WatchBuilder*) clear;
- (WatchBuilder*) clone;

- (Watch*) build;
- (Watch*) buildPartial;

- (WatchBuilder*) mergeFrom:(Watch*) other;
- (WatchBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (WatchBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt64) id;
- (WatchBuilder*) setId:(UInt64) value;
- (WatchBuilder*) clearId;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (WatchBuilder*) setNickName:(NSString*) value;
- (WatchBuilder*) clearNickName;

- (BOOL) hasNumber;
- (UInt64) number;
- (WatchBuilder*) setNumber:(UInt64) value;
- (WatchBuilder*) clearNumber;

- (BOOL) hasImsi;
- (UInt64) imsi;
- (WatchBuilder*) setImsi:(UInt64) value;
- (WatchBuilder*) clearImsi;

- (BOOL) hasImei;
- (UInt64) imei;
- (WatchBuilder*) setImei:(UInt64) value;
- (WatchBuilder*) clearImei;

- (BOOL) hasLocationType;
- (UInt32) locationType;
- (WatchBuilder*) setLocationType:(UInt32) value;
- (WatchBuilder*) clearLocationType;

- (BOOL) hasLon;
- (Float64) lon;
- (WatchBuilder*) setLon:(Float64) value;
- (WatchBuilder*) clearLon;

- (BOOL) hasLat;
- (Float64) lat;
- (WatchBuilder*) setLat:(Float64) value;
- (WatchBuilder*) clearLat;

- (BOOL) hasLocation;
- (NSString*) location;
- (WatchBuilder*) setLocation:(NSString*) value;
- (WatchBuilder*) clearLocation;

- (BOOL) hasBattery;
- (UInt32) battery;
- (WatchBuilder*) setBattery:(UInt32) value;
- (WatchBuilder*) clearBattery;

- (BOOL) hasAge;
- (UInt32) age;
- (WatchBuilder*) setAge:(UInt32) value;
- (WatchBuilder*) clearAge;

- (BOOL) hasGrade;
- (UInt32) grade;
- (WatchBuilder*) setGrade:(UInt32) value;
- (WatchBuilder*) clearGrade;

- (BOOL) hasAvatar;
- (NSString*) avatar;
- (WatchBuilder*) setAvatar:(NSString*) value;
- (WatchBuilder*) clearAvatar;

- (BOOL) hasGender;
- (UInt32) gender;
- (WatchBuilder*) setGender:(UInt32) value;
- (WatchBuilder*) clearGender;

- (BOOL) hasHeight;
- (UInt32) height;
- (WatchBuilder*) setHeight:(UInt32) value;
- (WatchBuilder*) clearHeight;

- (BOOL) hasWeight;
- (UInt32) weight;
- (WatchBuilder*) setWeight:(UInt32) value;
- (WatchBuilder*) clearWeight;

- (BOOL) hasLoveCount;
- (UInt32) loveCount;
- (WatchBuilder*) setLoveCount:(UInt32) value;
- (WatchBuilder*) clearLoveCount;

- (BOOL) hasStatus;
- (UInt32) status;
- (WatchBuilder*) setStatus:(UInt32) value;
- (WatchBuilder*) clearStatus;

- (NSMutableArray *)locations;
- (Location*)locationsAtIndex:(NSUInteger)index;
- (WatchBuilder *)addLocations:(Location*)value;
- (WatchBuilder *)setLocationsArray:(NSArray *)array;
- (WatchBuilder *)clearLocations;

- (BOOL) hasVolume;
- (UInt32) volume;
- (WatchBuilder*) setVolume:(UInt32) value;
- (WatchBuilder*) clearVolume;

- (BOOL) hasQrCode;
- (NSString*) qrCode;
- (WatchBuilder*) setQrCode:(NSString*) value;
- (WatchBuilder*) clearQrCode;

- (BOOL) hasQrCodePic;
- (NSData*) qrCodePic;
- (WatchBuilder*) setQrCodePic:(NSData*) value;
- (WatchBuilder*) clearQrCodePic;

- (BOOL) hasLatestLoginTime;
- (UInt64) latestLoginTime;
- (WatchBuilder*) setLatestLoginTime:(UInt64) value;
- (WatchBuilder*) clearLatestLoginTime;

- (BOOL) hasLightSensorOn;
- (UInt32) lightSensorOn;
- (WatchBuilder*) setLightSensorOn:(UInt32) value;
- (WatchBuilder*) clearLightSensorOn;

- (BOOL) hasLightSensorStatus;
- (UInt32) lightSensorStatus;
- (WatchBuilder*) setLightSensorStatus:(UInt32) value;
- (WatchBuilder*) clearLightSensorStatus;

- (BOOL) hasGmotionOn;
- (UInt32) gmotionOn;
- (WatchBuilder*) setGmotionOn:(UInt32) value;
- (WatchBuilder*) clearGmotionOn;

- (BOOL) hasGmotionSteps;
- (UInt32) gmotionSteps;
- (WatchBuilder*) setGmotionSteps:(UInt32) value;
- (WatchBuilder*) clearGmotionSteps;

- (BOOL) hasLangString;
- (UInt32) langString;
- (WatchBuilder*) setLangString:(UInt32) value;
- (WatchBuilder*) clearLangString;
@end

#define Location_arfcn @"arfcn"
#define Location_bsic @"bsic"
#define Location_rssi @"rssi"
#define Location_rxlev @"rxlev"
#define Location_mcc @"mcc"
#define Location_mnc @"mnc"
#define Location_lac @"lac"
#define Location_ci @"ci"
@interface Location : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasArfcn_:1;
  BOOL hasBsic_:1;
  BOOL hasRssi_:1;
  BOOL hasRxlev_:1;
  BOOL hasMcc_:1;
  BOOL hasMnc_:1;
  BOOL hasLac_:1;
  BOOL hasCi_:1;
  SInt32 arfcn;
  SInt32 bsic;
  SInt32 rssi;
  SInt32 rxlev;
  SInt32 mcc;
  SInt32 mnc;
  SInt32 lac;
  SInt32 ci;
}
- (BOOL) hasArfcn;
- (BOOL) hasBsic;
- (BOOL) hasRssi;
- (BOOL) hasRxlev;
- (BOOL) hasMcc;
- (BOOL) hasMnc;
- (BOOL) hasLac;
- (BOOL) hasCi;
@property (readonly) SInt32 arfcn;
@property (readonly) SInt32 bsic;
@property (readonly) SInt32 rssi;
@property (readonly) SInt32 rxlev;
@property (readonly) SInt32 mcc;
@property (readonly) SInt32 mnc;
@property (readonly) SInt32 lac;
@property (readonly) SInt32 ci;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LocationBuilder*) builder;
+ (LocationBuilder*) builder;
+ (LocationBuilder*) builderWithPrototype:(Location*) prototype;
- (LocationBuilder*) toBuilder;

+ (Location*) parseFromData:(NSData*) data;
+ (Location*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Location*) parseFromInputStream:(NSInputStream*) input;
+ (Location*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Location*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Location*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LocationBuilder : PBGeneratedMessageBuilder {
@private
  Location* resultLocation;
}

- (Location*) defaultInstance;

- (LocationBuilder*) clear;
- (LocationBuilder*) clone;

- (Location*) build;
- (Location*) buildPartial;

- (LocationBuilder*) mergeFrom:(Location*) other;
- (LocationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LocationBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasArfcn;
- (SInt32) arfcn;
- (LocationBuilder*) setArfcn:(SInt32) value;
- (LocationBuilder*) clearArfcn;

- (BOOL) hasBsic;
- (SInt32) bsic;
- (LocationBuilder*) setBsic:(SInt32) value;
- (LocationBuilder*) clearBsic;

- (BOOL) hasRssi;
- (SInt32) rssi;
- (LocationBuilder*) setRssi:(SInt32) value;
- (LocationBuilder*) clearRssi;

- (BOOL) hasRxlev;
- (SInt32) rxlev;
- (LocationBuilder*) setRxlev:(SInt32) value;
- (LocationBuilder*) clearRxlev;

- (BOOL) hasMcc;
- (SInt32) mcc;
- (LocationBuilder*) setMcc:(SInt32) value;
- (LocationBuilder*) clearMcc;

- (BOOL) hasMnc;
- (SInt32) mnc;
- (LocationBuilder*) setMnc:(SInt32) value;
- (LocationBuilder*) clearMnc;

- (BOOL) hasLac;
- (SInt32) lac;
- (LocationBuilder*) setLac:(SInt32) value;
- (LocationBuilder*) clearLac;

- (BOOL) hasCi;
- (SInt32) ci;
- (LocationBuilder*) setCi:(SInt32) value;
- (LocationBuilder*) clearCi;
@end

#define Mobile_id @"id"
#define Mobile_number @"number"
#define Mobile_nickName @"nickName"
#define Mobile_imsi @"imsi"
#define Mobile_imei @"imei"
#define Mobile_locationType @"locationType"
#define Mobile_lon @"lon"
#define Mobile_lat @"lat"
#define Mobile_location @"location"
#define Mobile_isAdmin @"isAdmin"
#define Mobile_uuid @"uuid"
#define Mobile_token @"token"
#define Mobile_code @"code"
@interface Mobile : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsAdmin_:1;
  BOOL hasLon_:1;
  BOOL hasLat_:1;
  BOOL hasId_:1;
  BOOL hasNumber_:1;
  BOOL hasImsi_:1;
  BOOL hasImei_:1;
  BOOL hasNickName_:1;
  BOOL hasLocation_:1;
  BOOL hasUuid_:1;
  BOOL hasToken_:1;
  BOOL hasCode_:1;
  BOOL hasLocationType_:1;
  BOOL isAdmin_:1;
  Float64 lon;
  Float64 lat;
  UInt64 id;
  UInt64 number;
  UInt64 imsi;
  UInt64 imei;
  NSString* nickName;
  NSString* location;
  NSString* uuid;
  NSString* token;
  NSString* code;
  UInt32 locationType;
}
- (BOOL) hasId;
- (BOOL) hasNumber;
- (BOOL) hasNickName;
- (BOOL) hasImsi;
- (BOOL) hasImei;
- (BOOL) hasLocationType;
- (BOOL) hasLon;
- (BOOL) hasLat;
- (BOOL) hasLocation;
- (BOOL) hasIsAdmin;
- (BOOL) hasUuid;
- (BOOL) hasToken;
- (BOOL) hasCode;
@property (readonly) UInt64 id;
@property (readonly) UInt64 number;
@property (readonly, strong) NSString* nickName;
@property (readonly) UInt64 imsi;
@property (readonly) UInt64 imei;
@property (readonly) UInt32 locationType;
@property (readonly) Float64 lon;
@property (readonly) Float64 lat;
@property (readonly, strong) NSString* location;
- (BOOL) isAdmin;
@property (readonly, strong) NSString* uuid;
@property (readonly, strong) NSString* token;
@property (readonly, strong) NSString* code;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (MobileBuilder*) builder;
+ (MobileBuilder*) builder;
+ (MobileBuilder*) builderWithPrototype:(Mobile*) prototype;
- (MobileBuilder*) toBuilder;

+ (Mobile*) parseFromData:(NSData*) data;
+ (Mobile*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Mobile*) parseFromInputStream:(NSInputStream*) input;
+ (Mobile*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Mobile*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Mobile*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface MobileBuilder : PBGeneratedMessageBuilder {
@private
  Mobile* resultMobile;
}

- (Mobile*) defaultInstance;

- (MobileBuilder*) clear;
- (MobileBuilder*) clone;

- (Mobile*) build;
- (Mobile*) buildPartial;

- (MobileBuilder*) mergeFrom:(Mobile*) other;
- (MobileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (MobileBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt64) id;
- (MobileBuilder*) setId:(UInt64) value;
- (MobileBuilder*) clearId;

- (BOOL) hasNumber;
- (UInt64) number;
- (MobileBuilder*) setNumber:(UInt64) value;
- (MobileBuilder*) clearNumber;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (MobileBuilder*) setNickName:(NSString*) value;
- (MobileBuilder*) clearNickName;

- (BOOL) hasImsi;
- (UInt64) imsi;
- (MobileBuilder*) setImsi:(UInt64) value;
- (MobileBuilder*) clearImsi;

- (BOOL) hasImei;
- (UInt64) imei;
- (MobileBuilder*) setImei:(UInt64) value;
- (MobileBuilder*) clearImei;

- (BOOL) hasLocationType;
- (UInt32) locationType;
- (MobileBuilder*) setLocationType:(UInt32) value;
- (MobileBuilder*) clearLocationType;

- (BOOL) hasLon;
- (Float64) lon;
- (MobileBuilder*) setLon:(Float64) value;
- (MobileBuilder*) clearLon;

- (BOOL) hasLat;
- (Float64) lat;
- (MobileBuilder*) setLat:(Float64) value;
- (MobileBuilder*) clearLat;

- (BOOL) hasLocation;
- (NSString*) location;
- (MobileBuilder*) setLocation:(NSString*) value;
- (MobileBuilder*) clearLocation;

- (BOOL) hasIsAdmin;
- (BOOL) isAdmin;
- (MobileBuilder*) setIsAdmin:(BOOL) value;
- (MobileBuilder*) clearIsAdmin;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (MobileBuilder*) setUuid:(NSString*) value;
- (MobileBuilder*) clearUuid;

- (BOOL) hasToken;
- (NSString*) token;
- (MobileBuilder*) setToken:(NSString*) value;
- (MobileBuilder*) clearToken;

- (BOOL) hasCode;
- (NSString*) code;
- (MobileBuilder*) setCode:(NSString*) value;
- (MobileBuilder*) clearCode;
@end

#define FamilyMember_id @"id"
#define FamilyMember_nickName @"nickName"
#define FamilyMember_number @"number"
#define FamilyMember_isAdmin @"isAdmin"
#define FamilyMember_watchIds @"watchIds"
#define FamilyMember_isFather @"isFather"
#define FamilyMember_isMother @"isMother"
@interface FamilyMember : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsAdmin_:1;
  BOOL hasIsFather_:1;
  BOOL hasIsMother_:1;
  BOOL hasId_:1;
  BOOL hasNumber_:1;
  BOOL hasNickName_:1;
  BOOL isAdmin_:1;
  BOOL isFather_:1;
  BOOL isMother_:1;
  UInt64 id;
  UInt64 number;
  NSString* nickName;
  PBAppendableArray * watchIdsArray;
}
- (BOOL) hasId;
- (BOOL) hasNickName;
- (BOOL) hasNumber;
- (BOOL) hasIsAdmin;
- (BOOL) hasIsFather;
- (BOOL) hasIsMother;
@property (readonly) UInt64 id;
@property (readonly, strong) NSString* nickName;
@property (readonly) UInt64 number;
- (BOOL) isAdmin;
@property (readonly, strong) PBArray * watchIds;
- (BOOL) isFather;
- (BOOL) isMother;
- (UInt64)watchIdsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FamilyMemberBuilder*) builder;
+ (FamilyMemberBuilder*) builder;
+ (FamilyMemberBuilder*) builderWithPrototype:(FamilyMember*) prototype;
- (FamilyMemberBuilder*) toBuilder;

+ (FamilyMember*) parseFromData:(NSData*) data;
+ (FamilyMember*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FamilyMember*) parseFromInputStream:(NSInputStream*) input;
+ (FamilyMember*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FamilyMember*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FamilyMember*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FamilyMemberBuilder : PBGeneratedMessageBuilder {
@private
  FamilyMember* resultFamilyMember;
}

- (FamilyMember*) defaultInstance;

- (FamilyMemberBuilder*) clear;
- (FamilyMemberBuilder*) clone;

- (FamilyMember*) build;
- (FamilyMember*) buildPartial;

- (FamilyMemberBuilder*) mergeFrom:(FamilyMember*) other;
- (FamilyMemberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FamilyMemberBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (UInt64) id;
- (FamilyMemberBuilder*) setId:(UInt64) value;
- (FamilyMemberBuilder*) clearId;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (FamilyMemberBuilder*) setNickName:(NSString*) value;
- (FamilyMemberBuilder*) clearNickName;

- (BOOL) hasNumber;
- (UInt64) number;
- (FamilyMemberBuilder*) setNumber:(UInt64) value;
- (FamilyMemberBuilder*) clearNumber;

- (BOOL) hasIsAdmin;
- (BOOL) isAdmin;
- (FamilyMemberBuilder*) setIsAdmin:(BOOL) value;
- (FamilyMemberBuilder*) clearIsAdmin;

- (PBAppendableArray *)watchIds;
- (UInt64)watchIdsAtIndex:(NSUInteger)index;
- (FamilyMemberBuilder *)addWatchIds:(UInt64)value;
- (FamilyMemberBuilder *)setWatchIdsArray:(NSArray *)array;
- (FamilyMemberBuilder *)setWatchIdsValues:(const UInt64 *)values count:(NSUInteger)count;
- (FamilyMemberBuilder *)clearWatchIds;

- (BOOL) hasIsFather;
- (BOOL) isFather;
- (FamilyMemberBuilder*) setIsFather:(BOOL) value;
- (FamilyMemberBuilder*) clearIsFather;

- (BOOL) hasIsMother;
- (BOOL) isMother;
- (FamilyMemberBuilder*) setIsMother:(BOOL) value;
- (FamilyMemberBuilder*) clearIsMother;
@end

#define Fence_name @"name"
#define Fence_lon @"lon"
#define Fence_lat @"lat"
#define Fence_radius @"radius"
@interface Fence : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasLon_:1;
  BOOL hasLat_:1;
  BOOL hasName_:1;
  BOOL hasRadius_:1;
  Float64 lon;
  Float64 lat;
  NSString* name;
  UInt32 radius;
}
- (BOOL) hasName;
- (BOOL) hasLon;
- (BOOL) hasLat;
- (BOOL) hasRadius;
@property (readonly, strong) NSString* name;
@property (readonly) Float64 lon;
@property (readonly) Float64 lat;
@property (readonly) UInt32 radius;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FenceBuilder*) builder;
+ (FenceBuilder*) builder;
+ (FenceBuilder*) builderWithPrototype:(Fence*) prototype;
- (FenceBuilder*) toBuilder;

+ (Fence*) parseFromData:(NSData*) data;
+ (Fence*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Fence*) parseFromInputStream:(NSInputStream*) input;
+ (Fence*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Fence*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Fence*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FenceBuilder : PBGeneratedMessageBuilder {
@private
  Fence* resultFence;
}

- (Fence*) defaultInstance;

- (FenceBuilder*) clear;
- (FenceBuilder*) clone;

- (Fence*) build;
- (Fence*) buildPartial;

- (FenceBuilder*) mergeFrom:(Fence*) other;
- (FenceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FenceBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasName;
- (NSString*) name;
- (FenceBuilder*) setName:(NSString*) value;
- (FenceBuilder*) clearName;

- (BOOL) hasLon;
- (Float64) lon;
- (FenceBuilder*) setLon:(Float64) value;
- (FenceBuilder*) clearLon;

- (BOOL) hasLat;
- (Float64) lat;
- (FenceBuilder*) setLat:(Float64) value;
- (FenceBuilder*) clearLat;

- (BOOL) hasRadius;
- (UInt32) radius;
- (FenceBuilder*) setRadius:(UInt32) value;
- (FenceBuilder*) clearRadius;
@end

#define Chat_type @"type"
#define Chat_time @"time"
#define Chat_nickName @"nickName"
#define Chat_text @"text"
#define Chat_datas @"datas"
#define Chat_watchIds @"watchIds"
#define Chat_mobileIds @"mobileIds"
@interface Chat : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasTime_:1;
  BOOL hasNickName_:1;
  BOOL hasText_:1;
  BOOL hasDatas_:1;
  BOOL hasType_:1;
  UInt64 time;
  NSString* nickName;
  NSString* text;
  NSData* datas;
  UInt32 type;
  PBAppendableArray * watchIdsArray;
  PBAppendableArray * mobileIdsArray;
}
- (BOOL) hasType;
- (BOOL) hasTime;
- (BOOL) hasNickName;
- (BOOL) hasText;
- (BOOL) hasDatas;
@property (readonly) UInt32 type;
@property (readonly) UInt64 time;
@property (readonly, strong) NSString* nickName;
@property (readonly, strong) NSString* text;
@property (readonly, strong) NSData* datas;
@property (readonly, strong) PBArray * watchIds;
@property (readonly, strong) PBArray * mobileIds;
- (UInt64)watchIdsAtIndex:(NSUInteger)index;
- (UInt64)mobileIdsAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ChatBuilder*) builder;
+ (ChatBuilder*) builder;
+ (ChatBuilder*) builderWithPrototype:(Chat*) prototype;
- (ChatBuilder*) toBuilder;

+ (Chat*) parseFromData:(NSData*) data;
+ (Chat*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Chat*) parseFromInputStream:(NSInputStream*) input;
+ (Chat*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Chat*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Chat*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ChatBuilder : PBGeneratedMessageBuilder {
@private
  Chat* resultChat;
}

- (Chat*) defaultInstance;

- (ChatBuilder*) clear;
- (ChatBuilder*) clone;

- (Chat*) build;
- (Chat*) buildPartial;

- (ChatBuilder*) mergeFrom:(Chat*) other;
- (ChatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ChatBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasType;
- (UInt32) type;
- (ChatBuilder*) setType:(UInt32) value;
- (ChatBuilder*) clearType;

- (BOOL) hasTime;
- (UInt64) time;
- (ChatBuilder*) setTime:(UInt64) value;
- (ChatBuilder*) clearTime;

- (BOOL) hasNickName;
- (NSString*) nickName;
- (ChatBuilder*) setNickName:(NSString*) value;
- (ChatBuilder*) clearNickName;

- (BOOL) hasText;
- (NSString*) text;
- (ChatBuilder*) setText:(NSString*) value;
- (ChatBuilder*) clearText;

- (BOOL) hasDatas;
- (NSData*) datas;
- (ChatBuilder*) setDatas:(NSData*) value;
- (ChatBuilder*) clearDatas;

- (PBAppendableArray *)watchIds;
- (UInt64)watchIdsAtIndex:(NSUInteger)index;
- (ChatBuilder *)addWatchIds:(UInt64)value;
- (ChatBuilder *)setWatchIdsArray:(NSArray *)array;
- (ChatBuilder *)setWatchIdsValues:(const UInt64 *)values count:(NSUInteger)count;
- (ChatBuilder *)clearWatchIds;

- (PBAppendableArray *)mobileIds;
- (UInt64)mobileIdsAtIndex:(NSUInteger)index;
- (ChatBuilder *)addMobileIds:(UInt64)value;
- (ChatBuilder *)setMobileIdsArray:(NSArray *)array;
- (ChatBuilder *)setMobileIdsValues:(const UInt64 *)values count:(NSUInteger)count;
- (ChatBuilder *)clearMobileIds;
@end

#define Setting_refuseStranger @"refuseStranger"
#define Setting_factoryReset @"factoryReset"
@interface Setting : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasRefuseStranger_:1;
  BOOL hasFactoryReset_:1;
  BOOL refuseStranger_:1;
  BOOL factoryReset_:1;
}
- (BOOL) hasRefuseStranger;
- (BOOL) hasFactoryReset;
- (BOOL) refuseStranger;
- (BOOL) factoryReset;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SettingBuilder*) builder;
+ (SettingBuilder*) builder;
+ (SettingBuilder*) builderWithPrototype:(Setting*) prototype;
- (SettingBuilder*) toBuilder;

+ (Setting*) parseFromData:(NSData*) data;
+ (Setting*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Setting*) parseFromInputStream:(NSInputStream*) input;
+ (Setting*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Setting*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Setting*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SettingBuilder : PBGeneratedMessageBuilder {
@private
  Setting* resultSetting;
}

- (Setting*) defaultInstance;

- (SettingBuilder*) clear;
- (SettingBuilder*) clone;

- (Setting*) build;
- (Setting*) buildPartial;

- (SettingBuilder*) mergeFrom:(Setting*) other;
- (SettingBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SettingBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasRefuseStranger;
- (BOOL) refuseStranger;
- (SettingBuilder*) setRefuseStranger:(BOOL) value;
- (SettingBuilder*) clearRefuseStranger;

- (BOOL) hasFactoryReset;
- (BOOL) factoryReset;
- (SettingBuilder*) setFactoryReset:(BOOL) value;
- (SettingBuilder*) clearFactoryReset;
@end

#define Alarm_enable @"enable"
#define Alarm_weekDay @"weekDay"
#define Alarm_time @"time"
#define Alarm_bell @"bell"
@interface Alarm : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasEnable_:1;
  BOOL hasWeekDay_:1;
  BOOL hasTime_:1;
  BOOL hasBell_:1;
  BOOL enable_:1;
  UInt32 weekDay;
  UInt32 time;
  UInt32 bell;
}
- (BOOL) hasEnable;
- (BOOL) hasWeekDay;
- (BOOL) hasTime;
- (BOOL) hasBell;
- (BOOL) enable;
@property (readonly) UInt32 weekDay;
@property (readonly) UInt32 time;
@property (readonly) UInt32 bell;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (AlarmBuilder*) builder;
+ (AlarmBuilder*) builder;
+ (AlarmBuilder*) builderWithPrototype:(Alarm*) prototype;
- (AlarmBuilder*) toBuilder;

+ (Alarm*) parseFromData:(NSData*) data;
+ (Alarm*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Alarm*) parseFromInputStream:(NSInputStream*) input;
+ (Alarm*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Alarm*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Alarm*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface AlarmBuilder : PBGeneratedMessageBuilder {
@private
  Alarm* resultAlarm;
}

- (Alarm*) defaultInstance;

- (AlarmBuilder*) clear;
- (AlarmBuilder*) clone;

- (Alarm*) build;
- (Alarm*) buildPartial;

- (AlarmBuilder*) mergeFrom:(Alarm*) other;
- (AlarmBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (AlarmBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEnable;
- (BOOL) enable;
- (AlarmBuilder*) setEnable:(BOOL) value;
- (AlarmBuilder*) clearEnable;

- (BOOL) hasWeekDay;
- (UInt32) weekDay;
- (AlarmBuilder*) setWeekDay:(UInt32) value;
- (AlarmBuilder*) clearWeekDay;

- (BOOL) hasTime;
- (UInt32) time;
- (AlarmBuilder*) setTime:(UInt32) value;
- (AlarmBuilder*) clearTime;

- (BOOL) hasBell;
- (UInt32) bell;
- (AlarmBuilder*) setBell:(UInt32) value;
- (AlarmBuilder*) clearBell;
@end

#define Lock_enable @"enable"
#define Lock_weekDay @"weekDay"
#define Lock_startTime @"startTime"
#define Lock_endTime @"endTime"
@interface Lock : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasEnable_:1;
  BOOL hasWeekDay_:1;
  BOOL hasStartTime_:1;
  BOOL hasEndTime_:1;
  BOOL enable_:1;
  UInt32 weekDay;
  UInt32 startTime;
  UInt32 endTime;
}
- (BOOL) hasEnable;
- (BOOL) hasWeekDay;
- (BOOL) hasStartTime;
- (BOOL) hasEndTime;
- (BOOL) enable;
@property (readonly) UInt32 weekDay;
@property (readonly) UInt32 startTime;
@property (readonly) UInt32 endTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (LockBuilder*) builder;
+ (LockBuilder*) builder;
+ (LockBuilder*) builderWithPrototype:(Lock*) prototype;
- (LockBuilder*) toBuilder;

+ (Lock*) parseFromData:(NSData*) data;
+ (Lock*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Lock*) parseFromInputStream:(NSInputStream*) input;
+ (Lock*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (Lock*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (Lock*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface LockBuilder : PBGeneratedMessageBuilder {
@private
  Lock* resultLock;
}

- (Lock*) defaultInstance;

- (LockBuilder*) clear;
- (LockBuilder*) clone;

- (Lock*) build;
- (Lock*) buildPartial;

- (LockBuilder*) mergeFrom:(Lock*) other;
- (LockBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (LockBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasEnable;
- (BOOL) enable;
- (LockBuilder*) setEnable:(BOOL) value;
- (LockBuilder*) clearEnable;

- (BOOL) hasWeekDay;
- (UInt32) weekDay;
- (LockBuilder*) setWeekDay:(UInt32) value;
- (LockBuilder*) clearWeekDay;

- (BOOL) hasStartTime;
- (UInt32) startTime;
- (LockBuilder*) setStartTime:(UInt32) value;
- (LockBuilder*) clearStartTime;

- (BOOL) hasEndTime;
- (UInt32) endTime;
- (LockBuilder*) setEndTime:(UInt32) value;
- (LockBuilder*) clearEndTime;
@end

#define PowerSwitch_openEnable @"openEnable"
#define PowerSwitch_openTime @"openTime"
#define PowerSwitch_closeEnable @"closeEnable"
#define PowerSwitch_closeTime @"closeTime"
@interface PowerSwitch : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOpenEnable_:1;
  BOOL hasCloseEnable_:1;
  BOOL hasOpenTime_:1;
  BOOL hasCloseTime_:1;
  BOOL openEnable_:1;
  BOOL closeEnable_:1;
  UInt32 openTime;
  UInt32 closeTime;
}
- (BOOL) hasOpenEnable;
- (BOOL) hasOpenTime;
- (BOOL) hasCloseEnable;
- (BOOL) hasCloseTime;
- (BOOL) openEnable;
@property (readonly) UInt32 openTime;
- (BOOL) closeEnable;
@property (readonly) UInt32 closeTime;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PowerSwitchBuilder*) builder;
+ (PowerSwitchBuilder*) builder;
+ (PowerSwitchBuilder*) builderWithPrototype:(PowerSwitch*) prototype;
- (PowerSwitchBuilder*) toBuilder;

+ (PowerSwitch*) parseFromData:(NSData*) data;
+ (PowerSwitch*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PowerSwitch*) parseFromInputStream:(NSInputStream*) input;
+ (PowerSwitch*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PowerSwitch*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PowerSwitch*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PowerSwitchBuilder : PBGeneratedMessageBuilder {
@private
  PowerSwitch* resultPowerSwitch;
}

- (PowerSwitch*) defaultInstance;

- (PowerSwitchBuilder*) clear;
- (PowerSwitchBuilder*) clone;

- (PowerSwitch*) build;
- (PowerSwitch*) buildPartial;

- (PowerSwitchBuilder*) mergeFrom:(PowerSwitch*) other;
- (PowerSwitchBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PowerSwitchBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasOpenEnable;
- (BOOL) openEnable;
- (PowerSwitchBuilder*) setOpenEnable:(BOOL) value;
- (PowerSwitchBuilder*) clearOpenEnable;

- (BOOL) hasOpenTime;
- (UInt32) openTime;
- (PowerSwitchBuilder*) setOpenTime:(UInt32) value;
- (PowerSwitchBuilder*) clearOpenTime;

- (BOOL) hasCloseEnable;
- (BOOL) closeEnable;
- (PowerSwitchBuilder*) setCloseEnable:(BOOL) value;
- (PowerSwitchBuilder*) clearCloseEnable;

- (BOOL) hasCloseTime;
- (UInt32) closeTime;
- (PowerSwitchBuilder*) setCloseTime:(UInt32) value;
- (PowerSwitchBuilder*) clearCloseTime;
@end


// @@protoc_insertion_point(global_scope)
